### ISSUE TITLE
Sharepoint-Services gradle dependency is not found

### ISSUE THREAD

**Issue by cjgehinscott** [OfficeDev/Office-365-SDK-for-Android#62]
The following gradle dependency for share point services is not found when adding it to my project:
compile group: 'com.microsoft.services', name: 'sharepoint-services', version: '0.11.1', ext:'aar'

The error I get is:

Error:Failed to find: com.microsoft.services:sharepoint-services:0.11.1
<a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Open in Project Structure dialog</a>

Is there a newer version or an update coming?

**Comment by marcote** [comment]
Hi @cjgehinscott 
I just tested it and I was able to retrieve the dependency with a new Android App created from scratch.
Used this : 
```
compile(group: 'com.microsoft.services', name: 'sharepoint-services', version: '0.11.1', ext: 'aar') 
``` 

Can you check it again please?

**Comment by cjgehinscott** [comment]
Thank you for the response.  It turns out the gradle dependency was being blocked by my company's firewall.  All is well now!

**Comment by marcote** [comment]
Cool.  Thanks
