### ISSUE TITLE
run into an OOM

### ISSUE THREAD

**Issue by Kammy6679** [OfficeDev/Office-365-SDK-for-Android#65]
Using the Office 365 SDK for Android and Office 365 SDK for iOS, we plan to access the OneDrive Business and stored data in our product.
 
We find that: our app runs into an OOM when using Office 365 SDK to upload/download a large file(about 30M or more). Do you have any suggestion for this issue?
 
Here is our download code:
SharePointClient client = ODB_Manager.getInstance().getFileClient();
ListenableFuture<byte[]> future = client.getfiles().getById(id).asFile().addHeader("if-none-match", eTag).getContent();
 
Here is our upload code:
ListenableFuture<Void> future = client.getfiles().getById(item.getid()).asFile().putContent(result);

**Comment by marcote** [comment]
@Kammy6679 

Hi have an initial implementation for this issue: 
https://github.com/OfficeDev/Office-365-SDK-for-Android/blob/dev/tests/e2e-test-app/app/src/main/java/com/microsoft/office365/test/integration/tests/FilesTests.java#L205

We're planning to release a new version including your request. 

Thanks,
Marcos

**Comment by Kammy6679** [comment]
Thank you Marcote. O(∩_∩)O~
We will try it.

**Comment by marcote** [comment]
@Kammy6679 we just released a new version with your request included. c3b68a34d407db1879ca19e21a8222d2efbc0ea7 
Thanks
