### ISSUE TITLE
The sharepoint-services module includes unnecessary Android resources

### ISSUE THREAD

**Issue by deadalusai** [OfficeDev/Office-365-SDK-for-Android#69]
Currently the `sharepoint-services` module includes apparently unnecessary string and drawable resources. This appears to interfere with any resources with the same name in consuming app code.

This screenshot shows Android Studio (0.9.9) treating the `ic_launcher.png` from `sharepoint-services` as alternatives of the same file in my own project resources.

![image](https://cloud.githubusercontent.com/assets/918952/6584843/ea8c9bf8-c7d2-11e4-8f22-a75488e23b0c.png)

At run time, the resource from the `sharepoint-services` (a default android icon) appears to be selected over my own resource.

**Comment by marcote** [comment]
Good catch. I will try to merge the PR today and release a new version tomorrow. 
Thanks!

**Comment by marcote** [comment]
Merged in with your PR in e9bf19b1e.  Thanks.
