### ISSUE TITLE
Can you delete folder by using the path name in one service call?

### ISSUE THREAD

**Issue by davidchesnut** [OfficeDev/Office-365-SDK-for-Android#71]
In the REST API you can delete a OneDrive folder in one call using the following approach:
DELETE {base-url}/getByPath('{folder-path}')

Is there a way to do this using the SDK? Currently I am obtaining the ID of the folder to delete first (one call) and then calling the delete method (second call).

//Find ID of the path
 Item folder = mSharePointClient.getfiles().getOperations().getByPath(fullPath).get();
 //Use ID to delete the folder
mSharePointClient.getfiles().getById(folder.getid()).addHeader(Constants.IF_MATCH_HEADER, "*").delete().get();

Thanks!
David

**Comment by marcote** [comment]
Not sure, but if you can point me to documentation where this operation is supported we can added into the SDK.
Ideally we should add methods supported by the public API. 
Makes sense?

**Comment by davechmsft** [comment]
Here's the topic I was looking at. https://msdn.microsoft.com/office/office365/APi/files-rest-operations#FolderoperationsDeleteafolder

Thanks!
David

**Comment by marcote** [comment]
I will take a look at this with the team at let you know.

**Comment by joshgav** [comment]
@davechmsft - Can you call `getByPath("folder/path").delete().get()`?

BTW @marcote `.delete().get()` is weird. I think it would be best if delete() implied end of chain and internally called get(). Add to backlog :)

**Comment by marcote** [comment]
@joshgav but Delete is the Future. `.get()`is the blocking call to the operation. I know it's weird, but IMO the correct approach is to return the future. Sadly get was not the greatest naming choice, but is outside our control.

What do you think?

**Comment by joshgav** [comment]
Ah okay, so `.get()` would be better named `.wait()` but it was Guava's choice. Okay then :)

**Comment by davechmsft** [comment]
@joshgav I do not see a delete method on getByPath(). Here is the code I'm currently using.
//Find ID of the path
        Item folder = mSharePointClient
                .getfiles()
                .getOperations()
                .getByPath(fullPath)
                .get();

        //Use ID to delete the folder
        mSharePointClient
                .getfiles()
                .getById(folder.getid())
                .addHeader(Constants.IF_MATCH_HEADER, "*")
                .delete()
                .get();

**Comment by davidchesnut** [comment]
Closing as this is an old issue overtaken by events.
