### ISSUE TITLE
Which version of ADAL to use

### ISSUE THREAD

**Issue by davechmsft** [OfficeDev/Office-365-SDK-for-Android#72]
The readme indicates to use ADAL version 1.0.5. The latest version is 1.1.2. Should we be using the readme version, or latest version when building apps that use the SDK?
Thanks!

**Comment by marcote** [comment]
Hi Dave. We tested it with 1.0.5. You can give it a try and let as know if some wrong arises with 1.1.2. We'll do the same.

Thanks.

**Comment by davechmsft** [comment]
Good to know the official tested version for this SDK. Thanks!

**Comment by Ricalo** [comment]
I've been using 1.1.1 for a while with no problems. I'll switch to 1.1.2 soon.

**Comment by marcote** [comment]
Thanks @Ricalo for the advice!
