### ISSUE TITLE
Recommend signout approach

### ISSUE THREAD

**Issue by davechmsft** [OfficeDev/Office-365-SDK-for-Android#73]
When building an app that supports signing out and signing in as a different user, what is the recommended method for signing out? Onc can clear the token cache. But to be thorough one can also clear the cookies from the Web session. This seems to be required if you used acquireToken with PromptBehavior set to Auto, as you then need to clear cookies to not remember the logged in user on the next acquireToken call. If acquireToken uses PromptBehavior set to Always, then we don't have to clear the cookies. What is the recommend approach to correctly sign out?
Thanks!

**Comment by marcote** [comment]
I think this a question more related to the ADAL team. Or at least their answer will be more definitive than ours. And if by any reason our flow is wrong we'll revisit it.
What do you think?

**Comment by davechmsft** [comment]
Makes sense. I will ask the question on the ADAL side.
Thanks!
