### ISSUE TITLE
Updating read status of message fails unless updateRaw is called

### ISSUE THREAD

**Issue by iambmelt** [OfficeDev/Office-365-SDK-for-Android#80]
I'm attempting to update the read status of a mail in exchange.

    // msgId is a msg in my Inbox
    Message msg = client.getMe().getMessage(msgId).read().get();
    msg.setIsRead(true);
    client.getMe().getMessage(msgId).update(msg).get();

returns:

    {
        "error": {
            "code": "ErrorInvalidPropertyUpdateSentMessage",
            "message": "Update operation is invalid for property of a sent message."
        }
    }

If I update the status via:

    client.getMe().getMessage(msgId).updateRaw("{\"IsRead\" : true}");

I get:

    200 OK

Environment:

    Nexus 6
    Android 5.1 - LMY47M
    K: 3.10.40-geec2459 android-build@vpbs1.mtv.corp.google.com #1 Wed Jan 28 22:14:35 UTC 2015
    Stock ROM
    Oracle jdk7

**Comment by anihojnadel** [comment]
@iambmelt This issue was fixed in today's release (v.0.14.2).
Thanks for contributing!!

**Comment by iambmelt** [comment]
@anihojnadel Thanks for the update! :+1:
