### ISSUE TITLE
Cannot resolve gradle dependencies

### ISSUE THREAD

**Issue by cjgehinscott** [OfficeDev/Office-365-SDK-for-Android#87]
Grade can't resolve the new version bump.

![screen shot 2015-06-05 at 3 43 35 pm](https://cloud.githubusercontent.com/assets/4421706/8013792/ad392b08-0b99-11e5-99f7-98244dfe0e85.png)
![screen shot 2015-06-05 at 3 43 43 pm](https://cloud.githubusercontent.com/assets/4421706/8013794/b0e7bc88-0b99-11e5-8fa5-2b9195804f38.png)

**Comment by marcote** [comment]
Hi @cjgehinscott . Artifacts have not been synced with jcenter yet. We're waiting for approval. In the mean time, please add the following lines into the repositories closure. The result should be something like this:

```
repositories {
    maven {
        url  "http://dl.bintray.com/msopentech/Maven" 
    }
}
````
I think the artifacts will sync with jcenter in some hours.

**Comment by marcote** [comment]
We just got the approval. Please try again.

**Comment by cjgehinscott** [comment]
I'm still getting the same error. Does it take a little bit once the sync happens for it to be accessible?  It wasn't working with the repository url added too.

On Jun 05, 2015, at 03:51 PM, Marcos Torres <notifications@github.com> wrote:

Hi @cjgehinscott . Artifacts have not been synced with jcenter yet. We're waiting for approval. In the mean time, please add the following lines into the repositories closure. The result should be something like this:
repositories { maven { url "http://dl.bintray.com/msopentech/Maven" } } 
I think the artifacts will sync with jcenter in some hours.

**Comment by joshgav** [comment]
Looks like it's our fault - the top line should be `com.microsoft.orc:orc-engine-android:0.14.1@aar`
Note that we may go to com.microsoft.services for the next release.

**Comment by joshgav** [comment]
Confirmed working now. Thanks @cjgehinscott for noting this right away!

**Comment by cjgehinscott** [comment]
Got it working. Thanks for your quick responses today, you guys are doing a great job!!

On Jun 05, 2015, at 06:59 PM, Josh Gavant <notifications@github.com> wrote:

Confirmed working now. Thanks @cjgehinscott for noting this right away!
