### ISSUE TITLE
Login doesn't works using normal Microsoft Acccount

### ISSUE THREAD

**Issue by forlayo** [OfficeDev/Office-365-SDK-for-Android#89]
Hello gentlemen,

I'm trying to do login with a normal Microsoft Account in order of access to my personal OneDrive storage account but I cannot do, steps of error are next ones:

1.- Start with login.
2.- Put personal Microsoft Account.
3.- When I select password field I'm getting redirected to another login screen.
4.- I do my login successfully and login returns to my application.
5.- On logcat logs I can see the following oauth error:
```
06-25 12:23:34.175  24505-12588/com.displaynote.solano V/Oauth﹕ 2015-06-25 10:23:34-7ecefa53-8832-4cc4-9061-d134276c0139-OAuth2 error:invalid_grant Description:AADSTS65001: No permission to access user information is configured for '0cef50d5-7299-4475-a41f-a67335109b3b' application, or it is expired or revoked.
    Trace ID: fe3ef703-ff83-4efe-85b4-8544fd37a1a9
    Correlation ID: 7ecefa53-8832-4cc4-9061-d134276c0139
    Timestamp: 2015-06-25 10:23:33Z ver:1.1.2
```
Using a corporative account from my company it works properly.

What I'm doing wrong ? I'm missing to set a permission into my Azure application ? ( These permission are a bit confusing )

I've configured following apps/permissions on my Azure application:

**Office 365 unified API (preview)**

* Edit or delete items in all site collections

* Read items in all site collections

* Read and write files that the user selects (preview)

* Read and Write access to user profile

* Enable sign-in and read user profile

**Windows Azure Active Directory**

* Enable sign-on and read users' profiles

* Access your organization's directory 

Thanks in advance, regards.

**Comment by marcote** [comment]
@forlayo OneDrive consumer requires a different SDK, which is not available yet. Not sure how are you accessing or what are you using to access your OneDrive contents.

**Comment by forlayo** [comment]
@marcote Oh.. :(. But why it redirects to OneDrive consumer login ? It's so difficult to control that user enters an account of OneDriver for bussiness or OneDrive consumer.. there's any way to disable this redirect ?.

There's an estimation for availability of SDK for OneDrive consumer ? should I use LiveSDK for this pourpose ?

Thanks a lot :)

**Comment by marcote** [comment]
@forlayo that's beyond my knowledge, I have no idea.
Regarding the availability of the OneDrive SDK, I would say soon. Maybe a couple of months and yes, the LiveSDK will be required (or something similar).

**Comment by forlayo** [comment]
@marcote Thanks a lot pal, I'll try to use LiveSDK for consumer an 365 SDK for bussiness..
