### ISSUE TITLE
Implement serializable in exceptions

### ISSUE THREAD

**Issue by Ricalo** [OfficeDev/Office-365-SDK-for-Android#91]
Hi,

I've been working with Visual Studio Application Insights and I find difficult to pass exceptions data to Application Insights.
The reason is because the Office 365 SDK exceptions don't implement Serializable, which is required to use the exception with the Application Insights SDK for Android.
Would you consider implementing Serializable in your exceptions?

**Comment by marcote** [comment]
Yes, of course. The code is frozen for 1.0.0 now, but it will be included in our next release, next week if everything goes fine.

**Comment by Ricalo** [comment]
Awesome. Thank you, @marcote!

**Comment by marcote** [comment]
@Ricalo one question. All exceptions in Java implements Serializable, and our OrcException extends java.lang.Exception. It's already serializable. Am I missing something?

**Comment by Ricalo** [comment]
Hi, @marcote.
Sorry for the late response,I took some days off work. I'm working with Office 365 SDK v0.13.0 and Application Insights v1.0-beta.5.
The Application Insights SDK chokes when trying to send the exception information by using 
```
TelemetryClient.getInstance().trackHandledException(Office365Exception);
```
with error java.io.NotSerializableException. If I send a raw java.lang.Exception it works fine.
However, I haven't updated to newer versions of the Office 365 SDK so I haven't tried sending the OrcException. That might solve the problem.

**Comment by marcote** [comment]
Ricalo, please re-open the issue if you still have problems.
