### ISSUE TITLE
Use Gradle wrapper

### ISSUE THREAD

**Issue by FabianFrank** [OfficeDev/Office-365-SDK-for-Android#92]
This is strongly recommended to make sure the correct version of gradle is used and there are no conflicts with other gradle installations on the host.

**Comment by marcote** [comment]
No, they don't. Android Studio creates the .gradle wrapper files for you (if you have an up to date version of AS). We can revisit this, of course.

**Comment by joshgav** [comment]
@FabianFrank we've discussed this and gone back and forth on whether to include the wrapper or not. Do you have examples of other projects or discussions where the wrappers are included in the repo? Any examples of a way to do it without creating a lot of extra clutter? Thanks!

**Comment by FabianFrank** [comment]
> The wrapper is something you should check into version control. By distributing the wrapper with your project, anyone can work with it without needing to install Gradle beforehand.
https://docs.gradle.org/current/userguide/gradle_wrapper.html

Some examples of popular Android projects that check in their gradle wrapper:
https://github.com/k9mail/k-9
https://github.com/nispok/snackbar
https://github.com/forkhubs/android
https://github.com/keyboardsurfer/Crouton

**Comment by joshgav** [comment]
Thanks! Marcos and I will review and reconsider.

**Comment by marcote** [comment]
We add the gradlew wrapper the repo. Thanks for the feedback.
