### ISSUE TITLE
Sample build depends on SDK build; SDK build depends on global props

### ISSUE THREAD

**Issue by FabianFrank** [OfficeDev/Office-365-SDK-for-Android#94]
```
ffrank@ffrank-ltm:~/git/Office-365-SDK-for-Android/samples/outlook (1) $ ~/gradle-2.2.1/bin/gradle assembleDebug

FAILURE: Build failed with an exception.

* Where:
Script '/Users/ffrank/git/Office-365-SDK-for-Android/sdk/library.gradle' line: 47

* What went wrong:
A problem occurred evaluating script.
> Could not find property 'bintrayUsername' on project ':outlook-services'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.94 secs
```

**Comment by marcote** [comment]
https://github.com/OfficeDev/Office-365-SDK-for-Android/blob/master/sdk/library.gradle#L48

**Comment by joshgav** [comment]
We should check for these props before using them, or only use them when the `uploadArchives` task is invoked.

**Comment by marcote** [comment]
We can supply dummy props, and they will get override if the prop is defined in ~/.gradle/gradle.properties . This will stop the evaluation error.

**Comment by joshgav** [comment]
Okay, that's a good stopgap, thanks @marcote. Can we remove the dependency on building the SDKs from the samples too?

**Comment by FabianFrank** [comment]
My recommendation would be to make the samples as close to what real world code would look like. Why not pull in the dependencies from jcenter?

**Comment by marcote** [comment]
We can and we should. :+1:

**Comment by marcote** [comment]
The samples and E2E now uses the artifacts deployed in bintray/jcenter. Also I fixed the mentioned evaluation error. If you still face issues, please re-open the issue.
