### ISSUE TITLE
getOperations() on OutlookClient returns null

### ISSUE THREAD

**Issue by FabianFrank** [OfficeDev/Office-365-SDK-for-Android#95]
I have `OutlookClient outlookClient = newOutlookClient (OUTLOOK_BASE_URL,myADALDependencyResolver);` and `outlookClient.getMe().getOperations` returns null when called. The samples look like `getMe().getOperations().sendMail()` is the correct chain of calls, however. There isn't anything in the logs that would indicate what's wrong.

Receiving lists of folders and lists of messages works fine, though. I have all email permissions enabled for my app.

**Comment by FabianFrank** [comment]
I am using the following dependencies:
```
    compile 'com.microsoft.services:outlook-services:1.0.0'
    compile 'com.microsoft.services.orc:orc-android:1.0.0@aar'
    compile 'com.microsoft.aad:adal:1.1.3@aar'
```

**Comment by marcote** [comment]
Strange, I'll take a look next Monday.

**Comment by FabianFrank** [comment]
Thanks @marcote, any ideas?

**Comment by marcote** [comment]
@FabianFrank I'll be reviewing this today. I'll let you know what I find.

**Comment by marcote** [comment]
Cannot reproduce the error. 
I tried both building the source code and the published aar without luck. 
Also I tried running our end2end test app : https://github.com/OfficeDev/Office-365-SDK-for-Android/tree/master/tests/e2e-test-app 

Specifically: https://github.com/OfficeDev/Office-365-SDK-for-Android/blob/master/tests/e2e-test-app/app/src/main/java/com/microsoft/office365/test/integration/tests/ExchangeTests.java#L816

These are the artifacts used:
````
compile 'com.microsoft.services:outlook-services:1.0.0'
compile(group: 'com.microsoft.services.orc', name: 'orc-android', version: '1.0.0', ext: 'aar')
```

I would like to see, if possible, a code snippet that reproduces the error.

**Comment by marcote** [comment]
I cannot reproduce this. Directory Services may need an special configuration, but the rest of the artifacts works fine. 
If you can reproduce the error, please re-open the issue.
